---

- name: check/install ntp client package
  apt:
    name: ntp
    state: latest
    update_cache: yes

- name: deploy ntp.conf to hosts
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    start_restart_ntp_client
